### ISSUE TITLE
Autostart PPTP Server on restart

### ISSUE THREAD

**Issue by marcoherbst** [evercam/vpn.evercam.io#2]
add to the file /etc/rc.local
service pptpd restart

**Comment by ijunaid8989** [comment]
As PPTPD was already a service, So there is no need to add it to `rc.local` for restart on every boot, instead of that, the better way is to enable that service on `systemctl` level with this command
```
sudo systemctl enable pptpd
```

Now on each reboot, the service will restart by itself. tested  and working fine.
